# Site settings
title: Abdullah Reza
email: air.reza@hotmail.com
url: https://rezaabdullah.github.io
description: "Blog on science, engineering and technology, particularly my journey into product development, engineering, AI/ML and data science projects."
keywords: "product development, product developer, solution architect, data science, data scientist, data, architect, full stack developer, nodejs, javascript, web developer, engineer, iot, ai, deep learning, machine learning, ai engineer, instrumentation, automation, protfolio"
skills: "Product Developer - ML/AI & IoT - Data Scientist - Agile Project Management"
meta_author: Reza Abdullah

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Abdullah Reza
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: http://linkedin.com/in/air.reza
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: github
    url: http://github.com/rezaabdullah
  
# Postal address (add as many lines as necessary)
address:
  - line: Petaling Jaya
  - line: Selangor 47301, Malaysia

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
